// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bQmJOEx452R1vQHocfpmELoEU3e9BVI',
    appId: '1:698820407192:web:761b98af999c14a03f85ed',
    messagingSenderId: '698820407192',
    projectId: 'kisaanunnati',
    authDomain: 'kisaanunnati.firebaseapp.com',
    storageBucket: 'kisaanunnati.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVuUfWCA6MYNfokrtPEYiR7NKNle_xcBI',
    appId: '1:698820407192:android:8ef9ab614a6eca833f85ed',
    messagingSenderId: '698820407192',
    projectId: 'kisaanunnati',
    storageBucket: 'kisaanunnati.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMz_fbPBZgUACV8do5jSLiAw50PITMoM',
    appId: '1:698820407192:ios:6e3a8b7e430fb41c3f85ed',
    messagingSenderId: '698820407192',
    projectId: 'kisaanunnati',
    storageBucket: 'kisaanunnati.firebasestorage.app',
    iosBundleId: 'com.example.kisanUnnati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKMz_fbPBZgUACV8do5jSLiAw50PITMoM',
    appId: '1:698820407192:ios:6e3a8b7e430fb41c3f85ed',
    messagingSenderId: '698820407192',
    projectId: 'kisaanunnati',
    storageBucket: 'kisaanunnati.firebasestorage.app',
    iosBundleId: 'com.example.kisanUnnati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bQmJOEx452R1vQHocfpmELoEU3e9BVI',
    appId: '1:698820407192:web:81fa8a77fccd0ab13f85ed',
    messagingSenderId: '698820407192',
    projectId: 'kisaanunnati',
    authDomain: 'kisaanunnati.firebaseapp.com',
    storageBucket: 'kisaanunnati.firebasestorage.app',
  );
}
